# See formats below:

    api_key = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    api_secret = 'YYYYYYYYYYYYYYYY'


# The followng are used in views.py

FLICKR_API_KEY = ''
FLICKR_API_SECRET = ''

INSTAGRAM_CLIENT_ID = ''
INSTAGRAM_CLIENT_SECRET = ''

NYTIMES_API_KEY = ""

PEARSON_API_KEY = ""

TUMBLR_API_KEY = ""

TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET = ''

TWITTER_KEY = ''
TWITTER_SECRET = ''

